#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)//copy & paste
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    autoSelector,   sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    vertGyro,       sensorGyro)
#pragma config(Sensor, in4,    accelY,         sensorAccelerometer)
#pragma config(Sensor, dgtl1,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDriveEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightDriveEnc,  sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  int_left_enc,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  int_right_enc,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           left_claw_motor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           front_right_drive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           bot_right_cat, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           back_right_drive, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           top_right_cat, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           top_left_cat,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           front_left_drive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           bot_left_cat,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           back_left_drive, tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          right_claw_motor, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   // Main competition background code provided by ROBOTC for VEX Robotics.
#include "SDrive.h"											// Including the Drive file.
#include "Catapult.h"										// Including the Catapult file.
#include "Autonomous - Copy.h"
#include "Display.h"


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
	//LcdAutonomousSelection();
	SensorValue(RightEncoder) = 0;

	SensorValue(gyro) = 0;
	wait1Msec(2000);
}

//int selector = 0;
task autonomous()
{
	string encoderValue, gyroValue;
	if(SensorValue(autoSelector) < 500)
	{
		auto1();
	}
	if(SensorValue(autoSelector) > 500 && SensorValue(autoSelector) < 1000)
	{
	  auto2();
	}
	if(SensorValue(autoSelector) > 1000 && SensorValue(autoSelector) < 1500)
	{
		auto3();
	}
	if(SensorValue(autoSelector) > 1500 && SensorValue(autoSelector) < 2000)
	{
		auto4();
	}
	if(SensorValue(autoSelector) > 2000 && SensorValue(autoSelector) < 2500)
	{
		auto5();
	}
	if(SensorValue(autoSelector) > 2500 && SensorValue(autoSelector) < 3000)
	{
		auto6();
	}
	if(SensorValue(autoSelector) > 3000 && SensorValue(autoSelector) < 3400)
	{
		auto7();
	}
	if(SensorValue(autoSelector) > 3400 && SensorValue(autoSelector) < 3800)
	{
		auto8();
	}
	if(SensorValue(autoSelector) > 3800)
	{
		skillsAuto();
	}
	//rampUp(30);
	//updateDriveMotors(0,0);
	//accelerate(30,400);
	//rampDown(127);
	//}
//	auto2();
	//if(selector == 1)
	//{
	//	auto1();
	//}
	//else if(selector == 2)
	//{
	//	auto2();
	//}
	//else if(selector == 3)
	//{
	//	auto3();
	//}
	//else if(selector == 4)
	//{
	//	auto4();
	//}
	//else if(selector == 5)
	//{
//		auto6();
	//}
	//else if(selector == 6)
	//{
	//	skillsAuto();
	//}
	//else if(selector == 7)
	//{
	//	testAuto();
	//}
	//displayLCDString(0, 0, "Gyro Angle: ");
	//sprintf(gyroValue, "%1.2f%c", SensorValue[vertGyro]/10);	//Build the value to be displayed
	//displayNextLCDString(gyroValue);

}


task usercontrol()
{
	//SensorValue[leftEncoder] = 0;
	//SensorValue[rightEncoder] = 0;
	bLCDBacklight = true;									// Turn on LCD Backlight

	string userSelect, uyen, omeed;

	while (true)
	{
		driveVariables();
		catVariables();//uyen,omeed

		//adjustCatapult();
		catapult();
		moveClaw();
		newDrive(driveY, driveX, strafe);
		clearIntegratedEncoders();
		raiseArmTeleop();
		score():
		calibrateArm();
		foldArm();
		driverSelect(omeed);

			if(scoreVal == 1)
			{
				displayLCDCenteredString(0, "¡3JO)S   ");
				displayLCDCenteredString(1, "SCORE!   ");
			}
			if(secretOVal == 1)
			{
				displayLCDCenteredString(0, "**GREAT JOB**");
				displayLCDCenteredString(1, "*OMEED!*");
			}
			if(secretUVal == 1)
			{
				displayLCDCenteredString(0, "**GREAT JOB**");
				displayLCDCenteredString(1, "*UYEN!*");
			}
			if(secretBVal == 1)
			{
				displayLCDCenteredString(0, "**GREAT JOB**");
				displayLCDCenteredString(1, "*BRIAN!*");
			}

		//setDisplay();
		//gyroClearLoop();
		//contingencyPlan();
		//display();
		//battDisp();
		//gyroEncDisp();
		//selectDriverDisp();
		// allDrive();

											// Clear line 2 (1) of the LCD

		//clearLCDLine(0);											// Clear line 1 (0) of the LCD
		//clearLCDLine(1);
		//displayLCDString(0, 0, "Primary: ");
		//	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		//	displayNextLCDString(mainBattery);

		//	//Display the Backup battery voltage
		//	displayLCDString(1, 0, "Backup: ");
		//	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		//	displayNextLCDString(backupBattery);
		/**/
	//displayLCDString(0, 0, "Enc Value: ");
	//		sprintf(encoderValue, "%1.2f%c", SensorValue[RightEncoder]);
	//		displayNextLCDString(encoderValue);

		//displayLCDString(0, 0, "Left Val: ");
		//sprintf(leftIntEnc, "%1.2f%c", SensorValue[leftDriveEnc]);
		//displayNextLCDString(leftIntEnc);

		/////**/
		//displayLCDString(1, 0, "Right Val: ");
		//sprintf(rightIntEnc, "%1.2f%c", SensorValue[rightDriveEnc]);	//Build the value to be displayed
		//displayNextLCDString(rightIntEnc);

		//displayLCDString(1, 0, "Gyro Val: ");
		//sprintf(accelerometer, "%1.2f%c", SensorValue[gyro]);	//Build the value to be displayed
		//displayNextLCDString(accelerometer);

		//displayLCDPos(0, 0);
	 // displayNextLCDString("Encoder: ");
	 // displayLCDPos(0, 7);
 	//  displayNextLCDNumber(SensorValue[RightEncoder], 4);
	 // displayLCDPos(0, 12);

		//if(abs(SensorValue[accel]) > 100)
		//{
		//	updateDriveMotors(-50,-50);
		//}
		//else if(abs(vexRT[Ch1]) < DEADZONE && abs(vexRT[Ch2]) < DEADZONE && abs(vexRT[Ch3]) < DEADZONE && abs(vexRT[Ch4]) < DEADZONE)
		//{
		//	updateDriveMotors(0,0);
		//}
		//Short delay for the LCD refresh rate

		if(scoreVal == 0 || secretOVal == 0 || secretUVal == 0 || secretBVal == 0)
		{
			if(SensorValue(autoSelector) < 500)
				displayLCDString(0, 0, "Auto 1 Selected");
			if(SensorValue(autoSelector) > 500 && SensorValue(autoSelector) < 1000)
			  displayLCDString(0, 0, "Auto 2 Selected");
			if(SensorValue(autoSelector) > 1000 && SensorValue(autoSelector) < 1500)
				displayLCDString(0, 0, "Auto 3 Selected");
			if(SensorValue(autoSelector) > 1500 && SensorValue(autoSelector) < 2000)
				displayLCDString(0, 0, "Auto 4 Selected");
			if(SensorValue(autoSelector) > 2000 && SensorValue(autoSelector) < 2500)
				displayLCDString(0, 0, "Auto 5 Selected");
			if(SensorValue(autoSelector) > 2500 && SensorValue(autoSelector) < 3000)
				displayLCDString(0, 0, "Auto 6 Selected");
			if(SensorValue(autoSelector) > 3000 && SensorValue(autoSelector) < 3400)
				displayLCDString(0, 0, "Auto 7 Selected");
			if(SensorValue(autoSelector) > 3400 && SensorValue(autoSelector) < 3800)
				displayLCDString(0, 0, "Auto 8 Selected");
			if(SensorValue(autoSelector) > 3800)
				displayLCDString(0, 0, "Skills Selected");
		}

		wait1Msec(100);
	}
}
/*
Dedicated to Team 599B: Shruti, Uyen, Ethan, Qusai, Juyeong, and Omeed
And a special thanks to our VEX World team: Aaron, Brian, Zach, Madeline, Carmina, Emily, Brandon, and Ian.
Without you, our VEX World dreams would have never come true.
*/
