
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

/*
Display Battery Voltage
ROBOTC on VEX 2.0 Cortex
This program uses the Display functions of ROBOTC on the VEX 2.0 Cortex platform.
It will display the value of the main battery on line 0 and backup battery on line 1.
ROBOT CONFIGURATION
MOTORS & SENSORS:
[I/O Port]					[Name]							[Type]								[Description
UART Port 2					none								VEX LCD								VEX LCD Screen
*/

task main()
{


	while(true)														// An infinite loop to keep the program running until you terminate it
	{

	}
}
